name: Build

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Current Build Time
        run: echo "BUILD_TIME=$(date +'%y-%m-%d %T')" >> "$GITHUB_ENV"
      - name: Before Build
        run: |
          printf 'BUILD_TIME: %s\n' "$BUILD_TIME"
          sed -i "s/VERSION/${{ github.ref_name }}/g" source/index.html.md
          sed -i "s/BUILD_TIME/$BUILD_TIME/g" source/index.html.md
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: slatedocs/slate:latest
          options: -v ${{ github.workspace }}/source:/srv/slate/source -v ${{ github.workspace }}/static:/srv/slate/build
          run: |
            cd /srv/slate
            /srv/slate/slate.sh build -v
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
          cname: func.dongfg.com
