name: Build

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Current Build Time
        id: cbt
        run: echo "::set-output name=time::$(date +'%y-%m-%d %T')"
      - name: Inject Version
        run: |
          sed -i "s/VERSION/${{ github.ref_name }}/g" source/index.html.md
          sed -i "s/BUILD_TIME/${{ steps.cbt.outputs.time }}/g" source/index.html.md
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: slatedocs/slate:latest
          options: -v ${{ github.workspace }}/source:/srv/slate/source -v ${{ github.workspace }}/static:/srv/slate/build
          run: |
            cd /srv/slate
            /srv/slate/slate.sh build -v
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
